name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    env:
      Solution_Name: wallet\wallet.sln  
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name
    - name: Build
      run: dotnet build $env:Solution_Name --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
